In [1]:
import optuna

In [2]:
!pip install optuna-dashboard

Requirement already satisfied: optuna-dashboard in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (0.20.0)
Requirement already satisfied: bottle>=0.13.0 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna-dashboard) (0.13.4)
Requirement already satisfied: optuna>=3.6.0 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna-dashboard) (4.6.0)
Requirement already satisfied: alembic>=1.5.0 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (1.18.1)
Requirement already satisfied: colorlog in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (6.10.1)
Requirement already satisfied: numpy in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (2.0.45)
Requirement already satisfied: tqdm in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (4.67.1)
Requirement already satisfied: PyYAML in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from optuna>=3.6.0->optuna-dashboard) (6.0.3)
Requirement already satisfied: Mako in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from alembic>=1.5.0->optuna>=3.6.0->optuna-dashboard) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from alembic>=1.5.0->optuna>=3.6.0->optuna-dashboard) (4.15.0)
Requirement already satisfied: greenlet>=1 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from sqlalchemy>=1.4.2->optuna>=3.6.0->optuna-dashboard) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/user/miniconda3/envs/vesuvius/lib/python3.11/site-packages (from Mako->alembic>=1.5.0->optuna>=3.6.0->optuna-dashboard) (3.0.3)

In [3]:
from optuna.storages import JournalStorage
from optuna.storages.journal import JournalFileBackend

storage = JournalStorage(
    JournalFileBackend("gbsa_journal.log")
)

study = optuna.load_study(study_name="gbsa_survival", storage=storage)

In [4]:
df = study.trials_dataframe()
df.head()

,number,value,datetime_start,datetime_complete,duration,params_ccp_alpha,params_dropout_rate,params_learning_rate,params_max_depth,params_max_features,params_max_leaf_nodes,params_min_impurity_decrease,params_min_samples_leaf,params_min_samples_split,params_n_estimators,params_n_iter_no_change,params_subsample,params_tol,params_validation_fraction,state
0,0,0.853891,2026-03-10 02:36:51.423395,2026-03-10 02:36:54.149104,0 days 00:00:02.725709,1.092959e-06,0.305926,0.154036,4,0.3,NaN,0.021597,11,7,218,20.0,0.865997,0.000040,0.127899,COMPLETE
1,1,0.826541,2026-03-10 02:36:54.163556,2026-03-10 02:37:14.563975,0 days 00:00:20.400419,1.520469e-06,0.260034,0.023076,4,0.3,NaN,0.033126,6,19,281,5.0,0.523225,0.004836,0.209342,COMPLETE
2,2,0.840792,2026-03-10 02:37:14.577484,2026-03-10 02:37:40.103866,0 days 00:00:25.526382,5.107754e-03,0.353429,0.132209,2,0.5,63.0,0.000276,4,16,319,NaN,0.544246,0.003884,0.245801,COMPLETE
3,3,0.815916,2026-03-10 02:37:40.109356,2026-03-10 02:38:08.688309,0 days 00:00:28.578953,1.659603e-08,0.318205,0.005773,2,0.3,16.0,0.005395,1,10,331,5.0,0.531779,0.001848,0.162871,COMPLETE
4,4,0.811980,2026-03-10 02:38:08.693393,2026-03-10 02:38:18.170271,0 days 00:00:09.476878,1.059532e-02,0.003476,0.001504,1,None,16.0,0.040901,9,6,153,NaN,0.644876,0.006741,0.202149,COMPLETE

In [5]:
df_sort = df.sort_values("value", ascending=False)
df_top20 = df_sort.head(20).drop(columns=["datetime_start", "datetime_complete", "duration", "state", "number",])
df_top20.to_csv("gbsa_top20.csv", index=False)
df_top20.head()

,value,params_ccp_alpha,params_dropout_rate,params_learning_rate,params_max_depth,params_max_features,params_max_leaf_nodes,params_min_impurity_decrease,params_min_samples_leaf,params_min_samples_split,params_n_estimators,params_n_iter_no_change,params_subsample,params_tol,params_validation_fraction
180,0.932300,3.387171e-06,0.010036,0.183752,5,1.0,NaN,0.001367,20,10,154,NaN,0.822759,0.000129,0.237531
238,0.931827,1.185231e-08,0.014365,0.110844,6,None,NaN,0.022981,13,17,358,NaN,0.849604,0.000161,0.253213
236,0.931186,1.893673e-08,0.004627,0.116992,6,None,NaN,0.012320,15,20,381,NaN,0.738513,0.000521,0.285868
229,0.930481,4.793502e-07,0.002454,0.088458,5,None,NaN,0.003652,18,14,219,NaN,0.772477,0.000107,0.265761
153,0.929977,8.280965e-05,0.009795,0.105618,5,1.0,31.0,0.021336,15,3,220,NaN,0.610098,0.000089,0.239808

In [6]:
df.describe()

,number,value,datetime_start,datetime_complete,duration,params_ccp_alpha,params_dropout_rate,params_learning_rate,params_max_depth,params_max_leaf_nodes,params_min_impurity_decrease,params_min_samples_leaf,params_min_samples_split,params_n_estimators,params_n_iter_no_change,params_subsample,params_tol,params_validation_fraction
count,300.000000,300.000000,300,300,300,3.000000e+02,300.000000,300.000000,300.000000,215.000000,300.000000,300.000000,300.000000,300.000000,190.000000,300.000000,300.000000,300.000000
mean,149.500000,0.890715,2026-03-10 02:59:20.307571712,2026-03-10 02:59:31.677410816,0 days 00:00:11.369839196,7.485123e-03,0.070318,0.109073,4.790000,23.213953,0.017334,11.786667,7.486667,220.496667,16.184211,0.803815,0.000862,0.250395
min,0.000000,0.811980,2026-03-10 02:36:51.423395,2026-03-10 02:36:54.149104,0 days 00:00:01.120865,1.011433e-08,0.001234,0.001085,1.000000,8.000000,0.000156,1.000000,2.000000,52.000000,5.000000,0.502366,0.000010,0.104863
25%,74.750000,0.872844,2026-03-10 02:45:38.395148544,2026-03-10 02:45:43.253001728,0 days 00:00:02.405780500,1.096019e-05,0.021863,0.062908,4.000000,16.000000,0.006588,8.000000,3.000000,112.500000,10.000000,0.717633,0.000045,0.228288
50%,149.500000,0.895145,2026-03-10 02:57:07.270555648,2026-03-10 02:57:13.500994560,0 days 00:00:05.179631500,4.060237e-04,0.053220,0.111364,5.000000,16.000000,0.014958,13.000000,6.000000,202.500000,20.000000,0.838536,0.000128,0.259521
75%,224.250000,0.913399,2026-03-10 03:08:47.111454208,2026-03-10 03:08:50.980964352,0 days 00:00:13.270378500,5.629931e-03,0.101380,0.152615,6.000000,31.000000,0.025835,15.000000,11.000000,319.000000,20.000000,0.923122,0.000704,0.278780
max,299.000000,0.932300,2026-03-10 03:33:43.992171,2026-03-10 03:33:45.695051,0 days 00:01:22.448043,9.145180e-02,0.462347,0.199506,6.000000,63.000000,0.049503,20.000000,20.000000,497.000000,20.000000,0.998505,0.009465,0.299450
std,86.746758,0.027661,NaN,NaN,0 days 00:00:14.936771491,1.582860e-02,0.068309,0.053658,1.196106,17.030506,0.012549,4.950709,5.427832,122.254258,6.067762,0.138378,0.001723,0.036760